version: '2'

services: 

  mariadb:
    image: daocloud.io/billqiang/docker-laravel-mariadb
    container_name: mariadb
    network_mode: host
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /data/compose/configs/mariadb/conf.d:/etc/mysql/conf.d
      - /data/compose/mariadb:/data/compose/mariadb
      - /data/log:/data/log
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  redis:
    image: daocloud.io/billqiang/docker-laravel-redis
    container_name: redis
    network_mode: host
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/compose/configs/redis/conf.d:/data/conf.d
      - /data/compose/redis:/data/redis
      - /data/log:/data/log

  mongo:
    network_mode: host
    container_name: mongo
    image: daocloud.io/billqiang/docker-laravel-mongodb
    entrypoint: [ "/usr/bin/mongod", "--config", "/etc/mongo/conf.d/mongod.conf"]
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /data/compose/mongo:/data/db
      - /data/log:/data/log
      - /data/compose/configs/mongo/conf.d:/etc/mongo/conf.d/

  php:
    image: daocloud.io/billqiang/docker-laravel-phpfpm
    container_name: php
    network_mode: host
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /data/code:/data/code
      - /data/log:/data/log

  go1:
    #image: daocloud.io/billqiang/docker-golang-scratch
    image: daocloud.io/billqiang/docker-golang
    container_name: go1
    network_mode: host
    restart: always
    environment:
        - APP_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - /data/log:/data/log
      - /data/code:/data/code
      - /data/code/wesee-api:/go/src/tapi

  go2:
    #image: daocloud.io/billqiang/docker-golang-scratch
    image: daocloud.io/billqiang/docker-golang
    container_name: go2
    network_mode: host
    restart: always
    environment:
        - APP_PORT=8081
    ports:
      - "8081:8080"
    volumes:
      - /data/log:/data/log
      - /data/code:/data/code
      - /data/code/wesee-api:/go/src/tapi

  go3:
    #image: daocloud.io/billqiang/docker-golang-scratch
    image: daocloud.io/billqiang/docker-golang
    container_name: go3
    network_mode: host
    restart: always
    environment:
        - APP_PORT=8082
    ports:
      - "8082:8080"
    volumes:
      - /data/log:/data/log
      - /data/code:/data/code
      - /data/code/wesee-api:/go/src/tapi

  nginx: 
    image: daocloud.io/billqiang/docker-laravel-nginx
    container_name: nginx
    network_mode: host
    restart: always
    ports:
      - "80"
      - "443"
    volumes:
      - /data/code:/data/code
      - /data/log:/data/log
      - /data/compose/configs/nginx/conf.d:/etc/nginx/conf.d/
